### ISSUE TITLE
timing of elementwise multiplication of ImageData

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#101]
I noticed a big timing difference in elementwise multiplication of two images using `ImageData` vs the corresponding `numpy arrays`

```python
x = data.OSEM_image
y = data.reference_image

%timeit x.multiply(y, out = x)
-> ca. 40ms
```

```python
xx = data.OSEM_image.as_array()       # takes ca 100ms
yy = data.reference_image.as_array()  # takes ca 100ms

%timeit zz = xx*yy
-> ca. 2ms
```

**Note**: the `as_array()` call takes `100ms`, so multiplying in numpy does not make sense in practice. But I was wondering why numpy's multiplication is so much faster than STIR's / whether there is a faster way to multiply to STIR ImageData objects.

**Comment by gschramm** [comment]
Ok. Just wanted to make sure that I am not overlooking sth.

**Comment by evgueni-ovtchinnikov** [comment]
@gschramm No wonder at all, this is how the multiplication is currently done:
```
	for (iter = data().begin_all(),
		iter_x = x.data().begin_all(), iter_y = y.data().begin_all();
		iter != data().end_all() &&
		iter_x != x.data().end_all() && iter_y != y.data().end_all();
		iter++, iter_x++, iter_y++)
		*iter = f(*iter_x, *iter_y);
```
Now that (I understand) STIR images are essentially one-dimensional arrays, the above loop can surely be optimized.
