### ISSUE TITLE
Script `create_initial_images.py` gets killed when executing `acquisition_model.set_up`

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/PETRIC#109]
I am having trouble working with `hofmann` data from Nicole on SIRF VM: `create_initial_images.py` gets killed when executing `acquisition_model.set_up(acquired_data, initial_image)`.

I put these info prints into `create_initial_images.py`:

- in `main` just before calling `create_acq_model_and_obj_fun`:
```
        print(acquired_data.shape)
        print(additive_term.shape)
        print(mult_factors.shape)
        print(template_image.shape)
        print(template_image.norm())
```
- in `create_acq_model_and_obj_fun` after calling `acquisition_model.set_up(acquired_data, initial_image)`:
```
print('acquisition_model.set_up ok')
```
and these debugging prints in `PETAcquisitionModel::set_up`:
```
std::cout << "in PETAcquisitionModel::set_up...\n";
	Succeeded s = Succeeded::no;
	if (sptr_projectors_.get()) {
std::cout << "setting up sptr_projectors_...\n";
const shared_ptr<const ProjDataInfo>& proj_data_info_sptr = sptr_acq->get_proj_data_info_sptr();
std::cout << "proj_data_info_sptr ok\n";
const shared_ptr<const ProjDataInfo>& proj_data_info_sptr_clone = proj_data_info_sptr->create_shared_clone();
std::cout << "proj_data_info_sptr_clone ok\n";
const shared_ptr<const DiscretisedDensity<3, float>>& image_sptr = sptr_image->data_sptr();
CartesianCoordinate3D<float> origin = image_sptr->get_origin();
std::cout << origin.x() << '\n';
std::cout << origin.y() << '\n';
std::cout << origin.z() << '\n';
std::cout << "image_sptr ok\n";
		s = sptr_projectors_->set_up(proj_data_info_sptr_clone, image_sptr);
//			(sptr_acq->get_proj_data_info_sptr()->create_shared_clone(),
//				sptr_image->data_sptr());
std::cout << "sptr_projectors_->set_up ok\n";
```

I tested these debugging prints on `mediso` data from Daniel, and I got
```
INFO:create_initial_images:Finding files in /home/sirfuser/mediso
INFO:create_initial_images:Constructing template image from prompts
(1, 1444, 324, 321)
(1, 1444, 324, 321)
(1, 1444, 324, 321)
(75, 155, 155)
0.0
in PETAcquisitionModel::set_up...
setting up sptr_projectors_...
proj_data_info_sptr ok
proj_data_info_sptr_clone ok
0
0
0
image_sptr ok
sptr_projectors_->set_up ok
acquisition_model.set_up ok
```
whereas for `hofmann` data I got:
```
INFO:create_initial_images:Finding files in /home/sirfuser/hofmann
INFO:create_initial_images:Constructing template image from prompts
(33, 815, 50, 520)
(33, 815, 50, 520)
(33, 815, 50, 520)
(159, 447, 447)
0.0
in PETAcquisitionModel::set_up...
setting up sptr_projectors_...
proj_data_info_sptr ok
proj_data_info_sptr_clone ok
0
0
0
image_sptr ok
Killed
```
Also, I get this message in `warnings.txt`:
WARNING: Expected the number of views (50) to be related to the number of detectors per ring (798), but this is not the case. Continuing anyway (but without adjusting the azimuthal angle offset).

**Comment by KrisThielemans** [comment]
I suspect that you're running out of memory. Probably best to use a system monitor (or `top` or similar in another window) to check memory usage while running.

> Also, I get this message in warnings.txt:
> WARNING: Expected the number of views (50) to be related to the number of detectors per ring (798), but this is not the case. Continuing anyway (but without adjusting the azimuthal angle offset).

yes, Siemens does some magic that we don't understand to get to 50. However, we do get descent images out, so you can ignore that particular warning.
