### ISSUE TITLE
Error reported by `PoissonLogLikelihoodWithLinearModelForMeanAndProjData.set_acquisition_model`

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/PETRIC#113]
When running `create_initial_images.py` on `hofmann` data, I get this error:
```
ERROR: BinNormalisation set-up with different ExamInfo.

Set_up was with
Time frame start - end (duration), all in secs: 0.0 - 1800.0 (1800.0)

Called with
Time frame start - end (duration), all in secs: 0.0 - 0.0 (0.0)
```
However, as I just have observed, nothing bad seems to happen with `mediso` data (from Daniel Deidda, NPL), so it looks like the culprit may be `hofmann`.

**Comment by KrisThielemans** [comment]
This was resolved by copying time information from `prompts.hs` to `additive_term.hs`. We need an adjustment to our conversion script therefore.
