### ISSUE TITLE
evaluation of branches

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#115]
In our repository, we have a couple of branches that are purely for testing (to be ignored in the evaluation).
Should we label those / declare which branches should be evaluated?

**Comment by KrisThielemans** [comment]
good point. Our "submit a tag" strategy doesn't really work very well with the evaluation phase. My feeling is to just keep branches that you want to submit, but I'm sure @casperdcl will have a plan.

**Comment by KrisThielemans** [comment]
https://github.com/SyneRBI/PETRIC/wiki#submission-via-github actually states
> For the final evaluation, we will consider only the latest commit on each branch of your repository.

So I guess you want to keep max 3 branches.

**Comment by casperdcl** [comment]
> Our "submit a tag" strategy doesn't really work very well with the evaluation phase.

what? why not?

I'd prefer if @gschramm you just tag any submission(s). Delete any debugging tags. I ignore branches so you can have as many debug branches as you want.

**Comment by gschramm** [comment]
@casperdcl We would also prefer to use tags (e.g. ALG1, ALG2, ALG3) (on different branches) to indicate which versions should be evaluated.

However, this is different from what is mentioned in the wiki (which might be confusing ...)

**Comment by gschramm** [comment]
If we agree that the evaluation is based on the available tags (max 3), we are happy to tag the versions to be considered.

**Comment by casperdcl** [comment]
I've fixed that section of the wiki now ([PETRIC/wiki/Recent-Updates](https://github.com/SyneRBI/PETRIC/wiki/Recent-Updates), [PETRIC/wiki#submission-via-github](https://github.com/SyneRBI/PETRIC/wiki#submission-via-github)).

We're using tags ;)
