### ISSUE TITLE
import petric.py still loads Siemens_mMR_NEMA_IQ, launches Tensorboard etc

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/PETRIC#117]
https://github.com/SyneRBI/PETRIC/blob/e5492379d630b3b221d74f6e43fd036a29029102/petric.py#L278-L284

This leads to surprising slowness, as well as problems if you don't have the data installed.

I'd prefer to remove this after the challenge is complete.

**Comment by casperdcl** [comment]
hopefully https://github.com/SyneRBI/PETRIC/blob/e5492379d630b3b221d74f6e43fd036a29029102/petric.py#L276 is enough?

**Comment by KrisThielemans** [comment]
It didn't work. Probably because there was a `data` directory.

**Comment by KrisThielemans** [comment]
These lines
https://github.com/SyneRBI/PETRIC/blob/bbb048f7e56385512332bed080edf02a2137dbfe/petric.py#L298-L305
means that all those metrics are created, even if we never want to use them.
