### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by mehrhardt** [SyneRBI/PETRIC#22]
### Team Name

TestMatthias

### Terms

- [X] (Optional) I want to be eligible for prizes, and will make my code public after the challenge ends.
- [X] I agree to abide by the [rules](https://github.com/SyneRBI/PETRIC/wiki).

**Comment by casperdcl** [comment]
Thanks @mehrhardt - did you want me to create a repo for you? If so, I'd like to fix #23 first :)

**Comment by mehrhardt** [comment]
Yes, that would be good. This is to test everything before our participants arrive.

**Comment by casperdcl** [comment]
Ok @mehrhardt I've created the private repository https://github.com/SyneRBI/PETRIC-TestMatthias.

Any tags you push to that repository will trigger a CI run which should in theory appear on the [leaderboard](https://petric.tomography.stfc.ac.uk/leaderboard/)
