### ISSUE TITLE
new registration team Leuven

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#27]
### Team Name

TeamLeuven1

### Terms

- [X] (Optional) I want to be eligible for prizes, and will make my code public after the challenge ends.
- [X] I agree to abide by the [rules](https://github.com/SyneRBI/PETRIC/wiki).

**Comment by casperdcl** [comment]
I've created the private repo https://github.com/SyneRBI/PETRIC-TeamLeuven1 and added you as an admin. Any tags you push will trigger a GPU CI run though all the data with results appearing on the leaderboard.
