### ISSUE TITLE
Neighborhood definition

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#29]
The wiki says:

>  $N_i$ the neighbourhood of voxel $i$ (here taken as the 8 nearest neighbours in the 3 directions),

What does that mean? I am a bit confused by the definition.
Do we have 8x3 = 24 out of 3x3x3=27 nearest neighbors?

A small drawing / sketch could help to clarify that.

Georg

**Comment by KrisThielemans** [comment]
Participants are actually required to use the SIRF RDP implementation, for the same reason as using the SIRF Parallelproj:
- emphasising algorithmic improvements over implementation 
- avoiding participants to have to dig into details
See also https://discord.com/channels/1242028164105109574/1252651306779152535/1259815364712464455

Apologies that this isn't clear. We'll do some rephrasing.

Regarding the actual question, I checked the STIR implementation https://github.com/UCL/STIR/blob/32befa6b19a3445c5b1522b3ef297a6def6786e7/src/recon_buildblock/RelativeDifferencePrior.cxx#L252-L266. It uses 3x3x3 actually (I thought the corners weren't included).

**Comment by KrisThielemans** [comment]
Wiki now states that participants have to use the `CudaRelativeDifferencePrior`
