### ISSUE TITLE
non-negativity constraint missing?

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#30]
In the description of the optimization problem in the wiki, the non-negativity constraint is not 
explicitly mentioned. I think most people will apply it automatically, but strictly speaking it
is in general not clear that the solution with the best cost is non-negative everywhere.

On the other hand, I think the RDP prior only makes sense for non-negative images, but
this is not obvious.

**Comment by KrisThielemans** [comment]
Thanks! I've aded x>=0 in the argmax. Please reopen if not sufficiently clear,
