### ISSUE TITLE
new registration

### ISSUE THREAD

**Issue by lucaxx85** [SyneRBI/PETRIC#38]
### Team Name

Tomo-Unimib

### GitHub users

ColomboMatte0

### Terms

- [X] (Optional) I want to be eligible for prizes, and will make my code public after the challenge ends.
- [X] I agree to abide by the [rules](https://github.com/SyneRBI/PETRIC/wiki).

**Comment by casperdcl** [comment]
You now have admin access to the private repository https://github.com/SyneRBI/PETRIC-Tomo-Unimib. Any *tags* you push will trigger a CI run on our GPUs & data, with results appearing on the [leaderboard](https://petric.tomography.stfc.ac.uk/leaderboard/).
