### ISSUE TITLE
clarify run-time

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/PETRIC#41]
Brought up by @ajreader: we need to clarify what is included in the measured run-time, i.e. loading if initial data (`get_data`) and our our callbacks (including metrics and saving) are not.

**Comment by casperdcl** [comment]
I somewhat disagree that this needs documenting given:

- it's an implementation detail
- the source code is public
- it's consistently applied to all submissions

If you want to update the wiki it's up to you, but personally if I was a participant I already find the wiki painfully unhelpfully obfuscatingly verbose.
