### ISSUE TITLE
one example notebook

### ISSUE THREAD

**Issue by paskino** [SyneRBI/PETRIC#5]
1. [x] download data https://github.com/TomographicImaging/SyneRBI-Challenge/blob/nema-data/src/SIRF_data_preparation/prepare_data.py
2. [x] run NEMA reconstruction (BSREM Algorithm) https://github.com/SyneRBI/SIRF-Contribs/blob/master/src/notebooks/BSREM_illustration.ipynb
3. [x] get ROIs https://github.com/SyneRBI/SIRF-Contribs/blob/master/src/Python/sirf/contrib/NEMA/generate_nema_rois.py
4. [x] run metrics https://github.com/TomographicImaging/Hackathon-000-Stochastic-QualityMetrics/blob/main/img_quality_cil_stir/image_quality_callback.py
   + [Challenge metrics.docx](https://liveuclac.sharepoint.com/:w:/s/CCPrenewal2019/EakE7S_OiadCmCcpX_IZD0kBECS-Cj2t5qxW2T0FxUv7DQ)
    + https://github.com/SyneRBI/PETRIC/blob/recon_with_metrics/metrics/NEMA-IQ-CIL.ipynb
5. [x] dummy Algorithm for users to implement custom reconstruction with

**Comment by KrisThielemans** [comment]
I think we can close this now, with the examples that we have.
