### ISSUE TITLE
monitor / verify usage of local GPU

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#64]
Hi all,

I was creating a small test script to estimate the computing time needed to
evaluate the complete data forward operator and it's adjoint (see below),
based on the main_OSEM example.

When I run the script which uses `STIR.AcquisitionModelUsingParallelproj`,
`nvidia-smi -l` claims that my GPU is not used at all. Is that to be expected?
I am running the docker contrainer as mentioned with `--gpus all`.

For the mMR and vision600, I obtain the following timing results for the
complete fwd / backward projections:

mMR: t_fwd = 6.6s, t_back = 10.1s
Vision600: t_fwd = 43s, t_back = 60s 

which seem indeed *long* to me when using parallelproj and my A4500.

```python
for srcdir, outdir, metrics in data_dirs_metrics:
        data = get_data(srcdir=srcdir, outdir=outdir)

        x = data.OSEM_image.clone()

        # find views in each subset
        # (note that SIRF can currently only do subsets over views)
        views = data.mult_factors.dimensions()[2]
        partitions_idxs = partition_indices(
            num_subsets, list(range(views)), stagger=True
        )

        # for each subset: find data, create acq_model, and create subset_sensitivity (backproj of 1)
        i = 0
        prompts_subset = data.acquired_data.get_subset(partitions_idxs[i])
        additive_term_subset = data.additive_term.get_subset(partitions_idxs[i])
        multiplicative_factors_subset = data.mult_factors.get_subset(partitions_idxs[i])

        acquisition_model_subset = STIR.AcquisitionModelUsingParallelproj()
        acquisition_model_subset.set_additive_term(additive_term_subset)
        acquisition_model_subset.set_up(prompts_subset, x)

        print(f"Timing forward projection - for 1 out of {num_subsets} subsets")
        t1 = time()
        for i in range(num_rep):
            x_fwd = acquisition_model_subset.forward(x)
        t2 = time()

        t_fwd_subset = (t2 - t1) / num_rep
        print(f"t fwd subset: {t_fwd_subset:.3f} s")
        print(f"t fwd: {num_subsets*t_fwd_subset:.3f} s")

        print(f"\nTiming back projection - for 1 out of {num_subsets} subsets")
        t1 = time()
        for i in range(num_rep):
            y_back = acquisition_model_subset.backward(multiplicative_factors_subset)
        t2 = time()

        t_back_subset = (t2 - t1) / num_rep
        print(f"t back subset: {t_back_subset:.3f} s")
        print(f"t back: {num_subsets*t_back_subset:.3f} s")
```

**Comment by KrisThielemans** [comment]
The above code doesn't set `num_subsets`. I'm guessing you ran it when it's set to 1?

Are you sure you're using `edge-gpu`, the latest one (if you've got one, you need to convince docker to pull the most recent)? `latest-gpu` actually didn't use the GPU...

By the way, I think that using the `out` argument for `forward` and `backward` would allow avoiding an extra allocation, which could be non-negligable (once your GPU is doing some work). (There will still be copying from device to host etc, unfortunately)

**Comment by gschramm** [comment]
1. I am indeed using `edge-gpu`, as mentioned in the README.
```
docker run --rm -it -v my_data_path:/mnt/share/petric:ro -v .:/workdir -w /workdir --gpus all synerbi/sirf:edge-gpu /bin/bash
```

2. `num_subsets=2` in the example and I am only using the first subset, but "extrapolating" to the full time by multiplying with `num_subsets`.

Do we have benchmarks on how long those operations "should" take on a state of the art CPU + GPU?

**Comment by gschramm** [comment]
pulling the latest `edge-gpu` solved it. In my older `edge-gpu` only the parallelproj_c lib was installed.

now `nvidia-smi` shows that my GPU is being used and the projections are much faster :)

closing the issue ...
