### ISSUE TITLE
cost function mentioned in main_OSEM.py

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#71]
https://github.com/SyneRBI/PETRIC/blob/d9fbdc0ea6a2d7c386ad1429f6bbc7fbfe4256ac/main_OSEM.py#L93

The cost function in main_OSEM.py is `sum(prompts * log(acq_model.forward(self.x)) - self.x * sensitivity)`.

Shouldn't that be:
`sum(prompts * log(acq_model.forward(self.x)) - acq_model.forward(self.x))` (plus prior)?

**Comment by KrisThielemans** [comment]
OSEM does NOT implement a MAP recon. https://github.com/SyneRBI/PETRIC/blob/d9fbdc0ea6a2d7c386ad1429f6bbc7fbfe4256ac/main_OSEM.py#L36

This example is provided to show yet another alternative how to implement a familiar algorithm, as well as giving the opportunity to compare OSEM metrics iwth MAP metrics.

Apologies if this isn't clear in the documentation, suggestions welcome (or maybe you didn't read it :smile)

**Comment by gschramm** [comment]
Indeed. But the cost function mentioned there also does not match the Poisson logL as far as I can see, which could confuse people if they want to evaluate cost (as sum of data fidelity + prior) themselves.

**Comment by KrisThielemans** [comment]
>  But the cost function mentioned there also does not match the Poisson logL as far as I can see, which could confuse people if they want to evaluate cost (as sum of data fidelity + prior) themselves.

Are you talking about the difference between
`sum(prompts * log(acq_model.forward(self.x)) - self.x * sensitivity)` and `sum(prompts * log(m*acq_model.forward(self.x)) - self.x * sensitivity)` (where the latter is the one mentioned on the wiki). That is indeed different. However, the difference is an image-independent constant, so should not affect any optimisation (and doesn't affect our metrics). One of the reasons I implemented `main_OSEM.py` that way is that it is faster (one multiplication and one division less per gradient).

Aside from thresholding, the former is an implementation of [6] https://github.com/UCL/STIR/issues/1472#issuecomment-2226308973, while the latter is one of [5]. Unfortunately, I'm planning to switch to [6] in STIR soon, which indeed will confuse people.

**Comment by gschramm** [comment]
Indeed. After writing it down, I see that the difference is only the sum of the known additive contamination, so indeed image-independent. 

`main_OSEM.py` is much appreciated and very helpful :)

**Comment by KrisThielemans** [comment]
>  I see that the difference is only the sum of the known additive contamination, so indeed image-independent.

multiplicative term `m` really: the difference is  `sum(prompts * log(m))`. The additive term cannot be taken out of the `log`.

By the way, this "trick" is our reason to write the accquisition model as $` D(m) (A x+a) `$

**Comment by gschramm** [comment]
Hm, now I am confused.

If we have an affine fwd mode:

$$
\bar{y} = Ax + b 
$$

and emission data $y$, the Poisson logL up to constant terms is:

$$
logL = \sum_i y_i \log{\bar{y}_i} - \sum_i \bar{y}_i
$$

If I understand your comment in the code correctly, you calculate (mathjaxx bug in a_{ij} ...)

$$
logL = \sum_i y_i \log{\bar{y}_i} - \sum_j x_j s_j =  \sum_i y_i \log{\bar{y}_i} - \sum_j x_j \sum_i a_ij 1
$$

which after swapping the last two sums is 

$$
logL = \sum_i y_i \log{\bar{y}_i} - \sum_i \sum_j a_ij x_j
$$

which is

$$
logL = \sum_i y_i \log{\bar{y}_i} - \sum_i (\bar{y}_i - b_i)
$$

isn't it?

**Comment by KrisThielemans** [comment]
nope... First of all, our wiki notation is different from yours. We use

$$ \hat{y} = D(m)(Ax + a) $$

so your $A$ is not ours... (and your $`\bar{y} `$ is our $` \hat(y) `$, with a funky Github rendering bug)).

Sticking to our notation, the `main_OSEM.py` suggests to compute
$`
O = \sum_i y_i \log{[A(x+a)]_i} - \sum_i \sum_j a_{ij} x_j
`$

which is (unless I'm making a typo!)

$$
O= \sum_i y_i (\log{\bar{y}_i - \log m_i)} - \sum_i (\bar{y}_i - b_i) = logL + csts
$$

**Comment by gschramm** [comment]
1. In the first definition of $O$, the operator $A$ is applied to $(x + a)$ (image + additive contamination in data space) which I guess is not correct? I think it should be $[Ax + a]_i$
2. I find it slightly confusing to use $a$ for the contaminations, if we use $a_{ij}$ for the matrix elements of $A$.

**Comment by KrisThielemans** [comment]
> 1. In the first definition of O, the operator A is applied to (x+a) (image + additive contamination in data space) which I guess is not correct? I think it should be [Ax+a]i

Indeed. Sorry

$`
O = \sum_i y_i \log{[(Ax)+a)]_i} - \sum_i \sum_j a_{ij} x_j
`$
> 2. I find it slightly confusing to use a for the contaminations, if we use aij for the matrix elements of A.

Apologies. We called it $a$ for "additive". I have not found any agreements on how to call this. (SIRF uses "background" for $b$).
