### ISSUE TITLE
metric names in tensorboard

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#72]
1. I am struggling to understand what the metrics labelled "AEM" in the tensorboard output represent
(see below). Do those correspond to the last metric mentioned in the wiki: 

```
(mean(recon,ROI) - mean(ref recon,ROI)) / mean(ref recon,background) 
```

and should be below 0.01? Or are those "unnormalized" absolute errors.

2. According the the wiki the RMSEs get normalized by the background ROI mean of the ref recon.
Are those values also reported in the tensorboard output?

![image](https://github.com/user-attachments/assets/04efb063-612a-4696-a3f2-2fde9284dd8b)

**Comment by KrisThielemans** [comment]
I think @casperdcl chose this name AEM for "absolute error of mean". Yes they are normalised. https://github.com/SyneRBI/PETRIC/blob/d9fbdc0ea6a2d7c386ad1429f6bbc7fbfe4256ac/petric.py#L134-L135

We're finalising our thresholds on Tuesday (sorry for delay), but metrics are reported ok now, AFAIK.

**Comment by KrisThielemans** [comment]
> Just to clarify, we use whole image background. We don't have ROI-specific backgrounds

Incorrect (!): we use the mean of the "background ROI". What that is, is phantom dependent (and decided by whoever provides the data. We just specify it's a ROI where activitiy is uniform and non-zero )

**Comment by casperdcl** [comment]
I have absolutely no idea what you are trying to say.

Please confirm this is correct https://github.com/SyneRBI/PETRIC/blob/d9fbdc0ea6a2d7c386ad1429f6bbc7fbfe4256ac/petric.py#L128-L136

**Comment by KrisThielemans** [comment]
it is correct. `self.norm` uses the "background ROI", You wrote above "we use whole image background".

**Comment by casperdcl** [comment]
- a "background" isn't an "ROI" because by definition it's not "interesting"
- by "whole image background" I mean "one background which corresponds to the whole image", i.e. a "phantom-specific background"
- we don't have "one background per ROI" i.e. lesion-specific backgrounds

**Comment by KrisThielemans** [comment]
> * a "background" isn't an "ROI" because by definition it's not "interesting"

https://github.com/SyneRBI/PETRIC/wiki#metrics-and-thresholds defines a "background ROI", which people can read and display. It is fairly standard terminology to say that if you have a cylinder with some activity and spheres with higher activity, to call the non-interesting (but crucial) stuff the "background". Again, what that "background" is, is phantom specific.

Confusing terminology? Probably. Can we change it? Not anymore.

> * by "whole image background" I mean "one background which corresponds to the whole image", i.e. a "phantom-specific background"

I'm sorry, but this is NOT what we compute. There is no "whole image" in our definition of the norm.

> * we don't have "one background per ROI" i.e. lesion-specific backgrounds

indeed we don't.

I suggest we leave discussion between organisers for Discord, as we're  at risk of confusing our participants (even more).

**Comment by gschramm** [comment]
> > * a "background" isn't an "ROI" because by definition it's not "interesting"
> 
> https://github.com/SyneRBI/PETRIC/wiki#metrics-and-thresholds defines a "background ROI", which people can read and display. It is fairly standard terminology to say that if you have a cylinder with some activity and spheres with higher activity, to call the non-interesting (but crucial) stuff the "background". Again, what that "background" is, is phantom specific (and it could be very interesting indeed).
> 
> Confusing terminology? Probably. Can we change it? Not anymore.
> 
> > * by "whole image background" I mean "one background which corresponds to the whole image", i.e. a "phantom-specific background"
> 
> I'm sorry, but this is NOT what we compute. There is no "whole image" in our definition of the norm.
> 
> > * we don't have "one background per ROI" i.e. lesion-specific backgrounds
> 
> indeed we don't.
> 
> I suggest we leave discussion between organisers for Discord, as we're at risk of confusing our participants (even more).

Agree, the only thing that needs to be clear for the participants is what to look at (e.g. in tensorboard) when they try to optimize their methods. For the ROI / background / whole background ... definition 1-2 images could be helpful.

**Comment by KrisThielemans** [comment]
https://petric.tomography.stfc.ac.uk/data contains pngs for VOIs for 2 of the phantoms. I note that the Vision600_thorax doesn't. I'll try to sync. (They should be generated via `data_QC.py`)

**Comment by KrisThielemans** [comment]
Right, I see that the figures that are there are a bit out-of-date, as `data_QC` now generates them centering the slices on the COM. Oh well. Regenerating I guess.

**Comment by gschramm** [comment]
@casperdcl which "time" (x-axis) should be focus on to measure the performance of our algorithms? To me "relative" seems to make most sense, but I am not sure whether the reported values are "recon iterations only" or also include the time needed to calculate the metrics.

**Comment by casperdcl** [comment]
yes it's "Relative"

**Comment by gschramm** [comment]
and does relative include the time needed to evaluate the metrics?
