### ISSUE TITLE
uploaded VOI figures are out-of-date

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/PETRIC#73]
`data_QC` now generates more useful figures by centering the slices on the COM of each VOI.

_Originally posted by @KrisThielemans in https://github.com/SyneRBI/PETRIC/issues/72#issuecomment-2242892811_

**Comment by gschramm** [comment]
It also seems that the .zips on folders on https://petric.tomography.stfc.ac.uk/data/ are not synced.
(which is why I was probably missing the ROI figures ...)

I think it might be safer to remove the / or force sync the zips to avoid confusion.

**Comment by gschramm** [comment]
downloading the files recursively from caddy seems not so straight forward. so I think force syncing the zips would make life easier for users.

**Comment by casperdcl** [comment]
@KrisThielemans whenever you make changes to the data, please run:

```sh
cd /mnt/share/petric; ls -d */ | sed s./.. | xargs -II zip -v -FS -r -o -9 I.zip I -x "*.png"
```

to update the `*.zip` files.
