### ISSUE TITLE
new registration

### ISSUE THREAD

**Issue by EzzatElmo** [SyneRBI/PETRIC#74]
### Team Name

IMT-NucI

### GitHub users

romarjor

### Terms

- [X] (Optional) I want to be eligible for prizes, and will make my code public after the challenge ends.
- [X] I agree to abide by the [rules](https://github.com/SyneRBI/PETRIC/wiki).

**Comment by casperdcl** [comment]
You (@EzzatElmo, @romarjor) now have admin access to the private repository <https://github.com/SyneRBI/PETRIC-IMT-NucI>.
Any *tags* you push will trigger a CI run on our GPUs & data, with results appearing on the [leaderboard](https://petric.tomography.stfc.ac.uk/leaderboard/).
