### ISSUE TITLE
leaderboard: objective functions are hard to interpret

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/PETRIC#85]
There are a few issues with how we plot the objective functions via TensorBoard:

- [BSREM](https://github.com/SyneRBI/PETRIC/blob/main/main_BSREM.py) maximises the SIRF objective function
- [ISTA](https://github.com/SyneRBI/PETRIC/blob/main/main_ISTA.py) minimises *minus* the SIRF objective function
- [OSEM](https://github.com/SyneRBI/PETRIC/blob/main/main_OSEM.py) maximises the SIRF log-likelihood, but `update_objective()` just does `return 0` (as it's not used by the OSEM `update()`)

We will not fix this, as:

- the objective function is not part of the metrics (#82)
- participants could use other conventions for the objective function (e.g. the CIL KL implementation uses a different offset)

We will keep the objective function on TensorBoard for now to help participants debug, but they will likely need to select/filter one algorithm at a time to benefit from y-axis autoscaling.

**Comment by casperdcl** [comment]
this issue is cross-referenced in https://github.com/SyneRBI/PETRIC/wiki/FAQ
