### ISSUE TITLE
factor 1/2 in RDP

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#87]
The SIRF documentation says that there is an additional factor of 1/2 in the RDP
https://github.com/SyneRBI/SIRF/blob/1e2c5c125df4216fc7bf593047f6056d94df3ae5/src/xSTIR/pSTIR/STIR.py#L2483
which is missing in the RDP description mentioned in the wiki.

As far as I can see from the STIR source code, the factor 1/2 is indeed there:
https://github.com/UCL/STIR/blob/e03fbd03976abdd543724aa2e1c2315fbd71e115/src/recon_buildblock/RelativeDifferencePrior.cxx#L282

**Comment by KrisThielemans** [comment]
FWiki fixed. thanks!
