### ISSUE TITLE
submission of several algorithms (using branches)

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#93]
If we want to submit several algorithms, the README says they have to be in the same repo, but on different branches.
Does that mean that when we create a tag, all remote branches are checked out?

Or do we have to "mark" remote branches that should be run and evaluated?

And is the branch name reflected in the leader board?

**Comment by gschramm** [comment]
After a 2nd thought, I think my question was stupid. I guess we have to create several tags on all branches.

**Comment by KrisThielemans** [comment]
yup. a tag in git is independent of the branch. you can tag any commit anywhere.
