### ISSUE TITLE
update_objective_interval = 10

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#94]
In all demo algorithms, `update_objective_interval = 10`. 

https://github.com/SyneRBI/PETRIC/blob/fb14c8772213da4852662344eec6dfca53a3b209/main_BSREM.py#L35

1. Are we allowed to change that value?
2. Does that value have an impact on the final evaluation? E.g., is there a wall time penalty for calculating the metrics?

**Comment by casperdcl** [comment]
as per #82:

- currently you can change it
- for final evaluation, we will override it to `np.inf` so it doesn't slow anything down (e.g. OSEM doesn't need an explicit objective calculation)

**Comment by KrisThielemans** [comment]
this should be closed as well?
