### ISSUE TITLE
conda error when installing deps from environment.yaml

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#95]
I added an environment.yml (see below) to install a few extra python packages. Unfortunately, when after pushing a tag the workflow fails with the error (see [here](https://github.com/SyneRBI/PETRIC-MaGeZ/actions/runs/10635488493/job/29485184326#step:4:52)):

```
CondaValueError: could not parse 'name: PETRIC-MAGEZ' in: environment.yml
```

My environment.yml contains
```
name: PETRIC-MAGEZ
channels: [conda-forge]
dependencies:
- my_package_1
- my_package_2
```

I guess I don't understand what the name of the conda env should be.

**Comment by KrisThielemans** [comment]
In my experience, the `name` thing is problem, and I just remove that line. Give it a go.

**Comment by gschramm** [comment]
still failing :( - now in the channels section 

https://github.com/SyneRBI/PETRIC-MaGeZ/actions/runs/10635744880/job/29486030531

```
CondaValueError: could not parse '- conda-forge' in: environment.yml
Error: Process completed with exit code 1.
```

**Comment by KrisThielemans** [comment]
I'm assuming you tried to use this locally, so I'm giving up.

**Comment by gschramm** [comment]
@casperdcl @paskino Locally, `conda/mamba env create -f environment.yml` works without problems (on linux and windows). I tried a couple of things (e.g. removing the name as suggested by Kris), but I always get the 
```
CondaValueError: could not parse 'name: petric_magez_alg_one' in: environment.yml
```
giving the content of the first line of `environment.yml`

**Comment by gschramm** [comment]
This could be issue:
https://stackoverflow.com/questions/58378971/conda-env-fails-to-create-new-environment

Are you using:
```
conda env create --file environment.yml
```
or
```
conda create --file environment.yml
```

the first one is the correct command.

**Comment by gschramm** [comment]
@KrisThielemans @casperdcl @paskino 
Found the problem in the gh worfklow (wrong conda command is used to install depedencies from yaml file and there shouls be no name in the environment.yaml).
PR is here:
https://github.com/SyneRBI/PETRIC-MaGeZ/pull/1

Discussion is here;
https://stackoverflow.com/questions/42352841/how-to-update-an-existing-conda-environment-with-a-yml-file

**Comment by casperdcl** [comment]
Thanks @gschramm - hopefully fixed now (try to re-push a tag)?

**Comment by gschramm** [comment]
thanks a lot Casper. Almost there (see below).

`conda env update` should be changed to
`conda env update -n base`

Any reason why you removed: `--file environment.yaml` ?

https://github.com/SyneRBI/PETRIC-MaGeZ/actions/runs/10664508401/job/29555905037#step:4:56

**Comment by casperdcl** [comment]
ergh... try now?

**Comment by gschramm** [comment]
Thanks a lot Casper. It's working now, and I can see ALG1_v1.0 of Team MaGeZ appearing on the leader board

**Comment by casperdcl** [comment]
P.S. You can always force-push a tag to overwrite leaderboard runs.

P.P.S. Also you can let me know if you want me to delete any leaderboard runs.

**Comment by casperdcl** [comment]
> You can delete all Team_MaGeZ/ALG1_* results

done :)
