### ISSUE TITLE
"new" data sets are missing in the leader board

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#98]
Seems that the leaderboard only contains the initial 3 data sets.

If possible, they (e.g. the mMR ACR data sets) should be added here:
https://github.com/SyneRBI/PETRIC/blob/50f28f0b97ad2d0a32f221ec1ca2d2f542194c2d/petric.py#L249

**Comment by KrisThielemans** [comment]
As we're getting new data ready, we will likely only automatically run 1 dataset from each scanner, to avoid overloading the STFC computing once people start to submit a lot of jobs (hopefully!).

You can run them locally by adjusting your own petric. Or maybe there's a smarter option...

**Comment by gschramm** [comment]
makes sense. I guess in principle there could be a decision based on the hostname in `petric.py` which data sets to run. 
(if the hostnames on STFC follow a pattern and it is safe to make that pattern public).

otherwise the decision could be made on a env. variable that users can set to run all data sets.

**Comment by KrisThielemans** [comment]
could be doable I guess. @casperdcl, What do you think? 5 min job?

**Comment by casperdcl** [comment]
you mean truncating the dataset list length in #91 using `int(os.getenv("PETRIC_MAX_DATASETS", "3"))` or similar?

**Comment by KrisThielemans** [comment]
let's leave it then. Participants can make this change themselves.
